version: "3.4"

services:
  app:
    build:
      context: .
      target: app
    ports: ["8000:8000", "8080:8080"]
    volumes: [".:/app"]
    working_dir: /app
    command: bin/console server:run 0.0.0.0:8000
  database:
    image: mysql:5.7
    ports: ["3307:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
