#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
app:
  path: /{path}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  requirements:
    path: .*
  defaults:
    template: index.html.twig
